const sceneDef = [
    {
        sceneNumber: 1,
        pathColliderURL: "./assets/stage_1/player path collider/output2.gltf",
        pathModelURL: "./assets/stage_1/player path/stage_1_path.gltf",
        modelURLArr: ["./assets/stage_1/models/output_3.gltf", "./assets/stage_1/models/output_4.gltf"],
        trackURL: "./assets/audio/track_1.mp3",
    },
    {
        sceneNumber: 2,
        pathColliderURL: "./assets/stage_1/player path collider/output2.gltf",
        pathModelURL: "./assets/stage_1/player path/stage_1_path.gltf",
        modelURLArr: ["./assets/stage_1/models/output_3.gltf", "./assets/stage_1/models/output_4.gltf"],
        trackURL: "./assets/audio/track_1.mp3",
    },
    {
        sceneNumber: 3,
        pathColliderURL: "./assets/stage_1/player path collider/output2.gltf",
        pathModelURL: "./assets/stage_1/player path/stage_1_path.gltf",
        modelURLArr: ["./assets/stage_1/models/output_3.gltf", "./assets/stage_1/models/output_4.gltf"],
        trackURL: "./assets/audio/track_1.mp3",
    },
    {
        sceneNumber: 4,
        pathColliderURL: "./assets/stage_1/player path collider/output2.gltf",
        pathModelURL: "./assets/stage_1/player path/stage_1_path.gltf",
        modelURLArr: ["./assets/stage_1/models/output_3.gltf", "./assets/stage_1/models/output_4.gltf"],
        trackURL: "./assets/audio/track_1.mp3",
    },
    {
        sceneNumber: 5,
        pathColliderURL: "./assets/stage_1/player path collider/output2.gltf",
        pathModelURL: "./assets/stage_1/player path/stage_1_path.gltf",
        modelURLArr: ["./assets/stage_1/models/output_3.gltf", "./assets/stage_1/models/output_4.gltf"],
        trackURL: "./assets/audio/track_1.mp3",
    },
    {
        sceneNumber: 6,
        pathColliderURL: "./assets/stage_1/player path collider/output2.gltf",
        pathModelURL: "./assets/stage_1/player path/stage_1_path.gltf",
        modelURLArr: ["./assets/stage_1/models/output_3.gltf", "./assets/stage_1/models/output_4.gltf"],
        trackURL: "./assets/audio/track_1.mp3",
    },
    {
        sceneNumber: 7,
        pathColliderURL: "./assets/stage_1/player path collider/output2.gltf",
        pathModelURL: "./assets/stage_1/player path/stage_1_path.gltf",
        modelURLArr: ["./assets/stage_1/models/output_3.gltf", "./assets/stage_1/models/output_4.gltf"],
        trackURL: "./assets/audio/track_1.mp3",
    },
    {
        sceneNumber: 8,
        pathColliderURL: "./assets/stage_1/player path collider/output2.gltf",
        pathModelURL: "./assets/stage_1/player path/stage_1_path.gltf",
        modelURLArr: ["./assets/stage_1/models/output_3.gltf", "./assets/stage_1/models/output_4.gltf"],
        trackURL: "./assets/audio/track_1.mp3",
    },
    {
        sceneNumber: 9,
        pathColliderURL: "./assets/stage_1/player path collider/output2.gltf",
        pathModelURL: "./assets/stage_1/player path/stage_1_path.gltf",
        modelURLArr: ["./assets/stage_1/models/output_3.gltf", "./assets/stage_1/models/output_4.gltf"],
        trackURL: "./assets/audio/track_1.mp3",
    },
    {
        sceneNumber: 10,
        pathColliderURL: "./assets/stage_1/player path collider/output2.gltf",
        pathModelURL: "./assets/stage_1/player path/stage_1_path.gltf",
        modelURLArr: ["./assets/stage_1/models/output_3.gltf", "./assets/stage_1/models/output_4.gltf"],
        trackURL: "./assets/audio/track_1.mp3",
    },
    {
        sceneNumber: 11,
        pathColliderURL: "./assets/stage_1/player path collider/output2.gltf",
        pathModelURL: "./assets/stage_1/player path/stage_1_path.gltf",
        modelURLArr: ["./assets/stage_1/models/output_3.gltf", "./assets/stage_1/models/output_4.gltf"],
        trackURL: "./assets/audio/track_1.mp3",
    },
    {
        sceneNumber: 12,
        pathColliderURL: "./assets/stage_1/player path collider/output2.gltf",
        pathModelURL: "./assets/stage_1/player path/stage_1_path.gltf",
        modelURLArr: ["./assets/stage_1/models/output_3.gltf", "./assets/stage_1/models/output_4.gltf"],
        trackURL: "./assets/audio/track_1.mp3",
    },
];
