const sceneDef = [
    {
        sceneNumber: 0,
        nextSceneNumber: 1,
        pathColliderURL: "./assets/chapter_1/player path collider/stage_3_path_collider.gltf",
        pathModelURL: "./assets/chapter_1/player path/stage_3_path.gltf",
        modelURLArr: [],
        trackURL: "./assets/audio/greenray.wav",
        initPos: [1.66, 3.5, 1.65],
    },
    {
        sceneNumber: 1,
        nextSceneNumber: 2,
        pathColliderURL: "./assets/chapter_1/player path collider/stage_3_path_collider.gltf",
        pathModelURL: "./assets/chapter_1/player path/stage_3_path.gltf",
        modelURLArr: [],
        trackURL: "./assets/audio/lemontea.wav",
        initPos: [1.66, 3.5, 1.65],
    },
    {
        sceneNumber: 2,
        nextSceneNumber: 3,
        pathColliderURL: "./assets/chapter_1/player path collider/stage_3_path_collider.gltf",
        pathModelURL: "./assets/chapter_1/player path/stage_3_path.gltf",
        modelURLArr: [],
        trackURL: "./assets/audio/variousthings.wav",
        initPos: [1.66, 3.5, 1.65],
    },
    {
        sceneNumber: 3,
        nextSceneNumber: 4,
        pathColliderURL: "./assets/chapter_1/player path collider/stage_3_path_collider.gltf",
        pathModelURL: "./assets/chapter_1/player path/stage_3_path.gltf",
        modelURLArr: [],
        trackURL: "./assets/audio/sigyeol.wav",
        initPos: [1.66, 3.5, 1.65],
    },
    {
        sceneNumber: 4,
        nextSceneNumber: 0,
        pathColliderURL: "./assets/chapter_1/player path collider/stage_3_path_collider.gltf",
        pathModelURL: "./assets/chapter_1/player path/stage_3_path.gltf",
        modelURLArr: [],
        trackURL: "./assets/audio/tailbone.wav",
        initPos: [1.66, 3.5, 1.65],
    },

    {
        sceneNumber: 5,
        nextSceneNumber: 6,
        pathColliderURL: "./assets/chapter_2/player path collider/stage_2_path_collider.gltf",
        pathModelURL: "./assets/chapter_2/player path/stage_2_path.gltf",
        modelURLArr: [
            "./assets/chapter_2/shared models/stage_2_columns.gltf",
            "./assets/chapter_2/shared models/stage_2_statues.gltf",
            "./assets/chapter_2/shared models/stage_2_dome.gltf",
        ],
        trackURL: "./assets/audio/girl.wav",
        initPos: [0, 0.3, 5],
    },
    {
        sceneNumber: 6,
        nextSceneNumber: 7,
        pathColliderURL: "./assets/chapter_2/player path collider/stage_2_path_collider.gltf",
        pathModelURL: "./assets/chapter_2/player path/stage_2_path.gltf",
        modelURLArr: [
            "./assets/chapter_2/shared models/stage_2_columns.gltf",
            "./assets/chapter_2/shared models/stage_2_statues.gltf",
            "./assets/chapter_2/shared models/stage_2_dome.gltf",
        ],
        trackURL: "./assets/audio/mung.wav",
        initPos: [0, 0.3, 5],
    },
    {
        sceneNumber: 7,
        nextSceneNumber: 8,
        pathColliderURL: "./assets/chapter_2/player path collider/stage_2_path_collider.gltf",
        pathModelURL: "./assets/chapter_2/player path/stage_2_path.gltf",
        modelURLArr: [
            "./assets/chapter_2/shared models/stage_2_columns.gltf",
            "./assets/chapter_2/shared models/stage_2_statues.gltf",
            "./assets/chapter_2/shared models/stage_2_dome.gltf",
        ],
        trackURL: "./assets/audio/etan.wav",
        initPos: [0, 0.3, 5],
    },
    {
        sceneNumber: 8,
        nextSceneNumber: 5,
        pathColliderURL: "./assets/chapter_2/player path collider/stage_2_path_collider.gltf",
        pathModelURL: "./assets/chapter_2/player path/stage_2_path.gltf",
        modelURLArr: [
            "./assets/chapter_2/shared models/stage_2_columns.gltf",
            "./assets/chapter_2/shared models/stage_2_statues.gltf",
            "./assets/chapter_2/shared models/stage_2_dome.gltf",
        ],
        trackURL: "./assets/audio/sogak.wav",
        initPos: [0, 0.3, 5],
    },

    {
        sceneNumber: 9,
        nextSceneNumber: 10,
        pathColliderURL: "",
        pathModelURL: "",
        modelURLArr: ["./assets/chapter_3/stage_1/city_buildings.gltf", "./assets/chapter_3/stage_1/city_roads.gltf"],
        trackURL: "./assets/audio/rushhour.wav",
        initPos: [-0.1098, 5.242271, -1.07224],
    },
    {
        sceneNumber: 10,
        nextSceneNumber: 11,
        pathColliderURL: "",
        pathModelURL: "",
        modelURLArr: ["./assets/chapter_3/stage_1/city_buildings.gltf", "./assets/chapter_3/stage_1/city_roads.gltf"],
        trackURL: "./assets/audio/ktm.wav",
        initPos: [0.6, 0.01, -0.1],
    },
    {
        sceneNumber: 11,
        nextSceneNumber: 12,
        pathColliderURL: "",
        pathModelURL: "",
        modelURLArr: ["./assets/chapter_3/stage_1/city_buildings.gltf"],
        trackURL: "./assets/audio/kami.wav",
        initPos: [0.6, 0.01, -0.1],
    },
    {
        sceneNumber: 12,
        nextSceneNumber: 9,
        pathColliderURL: "",
        pathModelURL: "",
        modelURLArr: ["./assets/chapter_3/stage_1/city_buildings.gltf"],
        trackURL: "./assets/audio/982.wav",
        initPos: [0.6, 0.01, -0.1],
    },
];
