// const sceneDef = [
//     {
//         sceneNumber: 0,
//         nextSceneNumber: 1,
//         pathColliderURL: "./assets/chapter_1/player path collider/stage_3_path_collider.gltf",
//         pathModelURL: "./assets/chapter_1/player path/stage_3_path.gltf",
//         modelURLArr: [],
//         trackURL: "./assets/audio/sample.mp3",
//         initPos: [1.66, 3.5, 1.65],
//     },
//     {
//         sceneNumber: 1,
//         nextSceneNumber: 2,
//         pathColliderURL: "./assets/chapter_1/player path collider/stage_3_path_collider.gltf",
//         pathModelURL: "./assets/chapter_1/player path/stage_3_path.gltf",
//         modelURLArr: [],
//         trackURL: "./assets/audio/sample.mp3",
//         initPos: [1.66, 3.5, 1.65],
//     },
//     {
//         sceneNumber: 2,
//         nextSceneNumber: 3,
//         pathColliderURL: "./assets/chapter_1/player path collider/stage_3_path_collider.gltf",
//         pathModelURL: "./assets/chapter_1/player path/stage_3_path.gltf",
//         modelURLArr: [],
//         trackURL: "./assets/audio/sample.mp3",
//         initPos: [1.66, 3.5, 1.65],
//     },
//     {
//         sceneNumber: 3,
//         nextSceneNumber: 4,
//         pathColliderURL: "./assets/chapter_1/player path collider/stage_3_path_collider.gltf",
//         pathModelURL: "./assets/chapter_1/player path/stage_3_path.gltf",
//         modelURLArr: [],
//         trackURL: "./assets/audio/sample.mp3",
//         initPos: [1.66, 3.5, 1.65],
//     },
//     {
//         sceneNumber: 4,
//         nextSceneNumber: 0,
//         pathColliderURL: "./assets/chapter_1/player path collider/stage_3_path_collider.gltf",
//         pathModelURL: "./assets/chapter_1/player path/stage_3_path.gltf",
//         modelURLArr: [],
//         trackURL: "./assets/audio/sample.mp3",
//         initPos: [1.66, 3.5, 1.65],
//     },

//     {
//         sceneNumber: 5,
//         nextSceneNumber: 6,
//         pathColliderURL: "./assets/chapter_2/player path collider/stage_2_path_collider.gltf",
//         pathModelURL: "./assets/chapter_2/player path/stage_2_path.gltf",
//         modelURLArr: [
//             "./assets/chapter_2/shared models/stage_2_columns.gltf",
//             "./assets/chapter_2/shared models/stage_2_statues.gltf",
//             "./assets/chapter_2/shared models/stage_2_dome.gltf",
//         ],
//         trackURL: "./assets/audio/sample.mp3",
//         initPos: [0, 0.3, 5],
//     },
//     {
//         sceneNumber: 6,
//         nextSceneNumber: 7,
//         pathColliderURL: "./assets/chapter_2/player path collider/stage_2_path_collider.gltf",
//         pathModelURL: "./assets/chapter_2/player path/stage_2_path.gltf",
//         modelURLArr: [
//             "./assets/chapter_2/shared models/stage_2_columns.gltf",
//             "./assets/chapter_2/shared models/stage_2_statues.gltf",
//             "./assets/chapter_2/shared models/stage_2_dome.gltf",
//         ],
//         trackURL: "./assets/audio/sample.mp3",
//         initPos: [0, 0.3, 5],
//     },
//     {
//         sceneNumber: 7,
//         nextSceneNumber: 8,
//         pathColliderURL: "./assets/chapter_2/player path collider/stage_2_path_collider.gltf",
//         pathModelURL: "./assets/chapter_2/player path/stage_2_path.gltf",
//         modelURLArr: [
//             "./assets/chapter_2/shared models/stage_2_columns.gltf",
//             "./assets/chapter_2/shared models/stage_2_statues.gltf",
//             "./assets/chapter_2/shared models/stage_2_dome.gltf",
//         ],
//         trackURL: "./assets/audio/sample.mp3",
//         initPos: [0, 0.3, 5],
//     },
//     {
//         sceneNumber: 8,
//         nextSceneNumber: 5,
//         pathColliderURL: "./assets/chapter_2/player path collider/stage_2_path_collider.gltf",
//         pathModelURL: "./assets/chapter_2/player path/stage_2_path.gltf",
//         modelURLArr: [
//             "./assets/chapter_2/shared models/stage_2_columns.gltf",
//             "./assets/chapter_2/shared models/stage_2_statues.gltf",
//             "./assets/chapter_2/shared models/stage_2_dome.gltf",
//         ],
//         trackURL: "./assets/audio/sample.mp3",
//         initPos: [0, 0.3, 5],
//     },

//     {
//         sceneNumber: 9,
//         nextSceneNumber: 10,
//         pathColliderURL: "",
//         pathModelURL: "",
//         modelURLArr: ["./assets/chapter_3/stage_1/city_buildings.gltf", "./assets/chapter_3/stage_1/city_roads.gltf"],
//         trackURL: "./assets/audio/sample.mp3",
//         initPos: [-0.1098, 5.242271, -1.07224],
//     },
//     {
//         sceneNumber: 10,
//         nextSceneNumber: 11,
//         pathColliderURL: "",
//         pathModelURL: "",
//         modelURLArr: ["./assets/chapter_3/stage_1/city_buildings.gltf", "./assets/chapter_3/stage_1/city_roads.gltf"],
//         trackURL: "./assets/audio/sample.mp3",
//         initPos: [0.6, 0.01, -0.1],
//     },
//     {
//         sceneNumber: 11,
//         nextSceneNumber: 12,
//         pathColliderURL: "",
//         pathModelURL: "",
//         modelURLArr: ["./assets/chapter_3/stage_1/city_buildings.gltf"],
//         trackURL: "./assets/audio/sample.mp3",
//         initPos: [0.6, 0.01, -0.1],
//     },
//     {
//         sceneNumber: 12,
//         nextSceneNumber: 9,
//         pathColliderURL: "",
//         pathModelURL: "",
//         modelURLArr: ["./assets/chapter_3/stage_1/city_buildings.gltf"],
//         trackURL: "./assets/audio/sample.mp3",
//         initPos: [0.6, 0.01, -0.1],
//     },
// ];

const sceneDef = [
    {
        sceneNumber: 0,
        nextSceneNumber: 1,
        pathColliderURL: "./assets/chapter_1/player path collider/stage_3_path_collider.gltf",
        pathModelURL: "./assets/chapter_1/player path/stage_3_path.gltf",
        modelURLArr: [],
        modelNameArr: [],
        trackURL: "./assets/audio/greenray.mp3",
        initPos: [1.66, 3.5, 1.65],
    },
    {
        sceneNumber: 1,
        nextSceneNumber: 2,
        pathColliderURL: "./assets/chapter_1/player path collider/stage_3_path_collider.gltf",
        pathModelURL: "./assets/chapter_1/player path/stage_3_path.gltf",
        modelURLArr: [],
        modelNameArr: [],
        trackURL: "./assets/audio/lemontea.mp3",
        initPos: [1.66, 3.5, 1.65],
    },
    {
        sceneNumber: 2,
        nextSceneNumber: 3,
        pathColliderURL: "./assets/chapter_1/player path collider/stage_3_path_collider.gltf",
        pathModelURL: "./assets/chapter_1/player path/stage_3_path.gltf",
        modelURLArr: [],
        modelNameArr: [],
        trackURL: "./assets/audio/variousthings.mp3",
        initPos: [1.66, 3.5, 1.65],
    },
    {
        sceneNumber: 3,
        nextSceneNumber: 4,
        pathColliderURL: "./assets/chapter_1/player path collider/stage_3_path_collider.gltf",
        pathModelURL: "./assets/chapter_1/player path/stage_3_path.gltf",
        modelURLArr: [],
        modelNameArr: [],
        trackURL: "./assets/audio/sigyeol.mp3",
        initPos: [1.66, 3.5, 1.65],
    },
    {
        sceneNumber: 4,
        nextSceneNumber: 0,
        pathColliderURL: "./assets/chapter_1/player path collider/stage_3_path_collider.gltf",
        pathModelURL: "./assets/chapter_1/player path/stage_3_path.gltf",
        modelURLArr: [],
        modelNameArr: [],
        trackURL: "./assets/audio/tailbone.mp3",
        initPos: [1.38672, 0.62669, 0.10881],
    },

    {
        sceneNumber: 5,
        nextSceneNumber: 6,
        pathColliderURL: "./assets/chapter_2/player path collider/stage_2_path_collider.gltf",
        pathModelURL: "./assets/chapter_2/player path/stage_2_path.gltf",
        modelURLArr: [
            "./assets/chapter_2/shared models/stage_2_columns.gltf",
            "./assets/chapter_2/shared models/stage_2_statues.gltf",
            "./assets/chapter_2/shared models/stage_2_dome.gltf",
        ],
        modelNameArr: ["COLUMNS", "STATUES", "DOME"],
        trackURL: "./assets/audio/girl.mp3",
        initPos: [0, 0.3, 5],
    },
    {
        sceneNumber: 6,
        nextSceneNumber: 7,
        pathColliderURL: "./assets/chapter_2/player path collider/stage_2_path_collider.gltf",
        pathModelURL: "./assets/chapter_2/player path/stage_2_path.gltf",
        modelURLArr: [
            "./assets/chapter_2/shared models/stage_2_columns.gltf",
            "./assets/chapter_2/shared models/stage_2_statues.gltf",
            "./assets/chapter_2/shared models/stage_2_dome.gltf",
        ],
        modelNameArr: ["COLUMNS", "STATUES", "DOME"],
        trackURL: "./assets/audio/mung.mp3",
        initPos: [0, 0.3, 5],
    },
    {
        sceneNumber: 7,
        nextSceneNumber: 8,
        pathColliderURL: "./assets/chapter_2/player path collider/stage_2_path_collider.gltf",
        pathModelURL: "./assets/chapter_2/player path/stage_2_path.gltf",
        modelURLArr: [
            "./assets/chapter_2/shared models/stage_2_columns.gltf",
            "./assets/chapter_2/shared models/stage_2_statues.gltf",
            "./assets/chapter_2/shared models/stage_2_dome.gltf",
        ],
        modelNameArr: ["COLUMNS", "STATUES", "DOME"],
        trackURL: "./assets/audio/etan.mp3",
        initPos: [0, 0.3, 5],
    },
    {
        sceneNumber: 8,
        nextSceneNumber: 5,
        pathColliderURL: "./assets/chapter_2/player path collider/stage_2_path_collider.gltf",
        pathModelURL: "./assets/chapter_2/player path/stage_2_path.gltf",
        modelURLArr: [
            "./assets/chapter_2/shared models/stage_2_columns.gltf",
            "./assets/chapter_2/shared models/stage_2_statues.gltf",
            "./assets/chapter_2/shared models/stage_2_dome.gltf",
        ],
        modelNameArr: ["COLUMNS", "STATUES", "DOME"],
        trackURL: "./assets/audio/sogak.mp3",
        initPos: [0, 0.3, 5],
    },

    {
        sceneNumber: 9,
        nextSceneNumber: 10,
        pathColliderURL: "",
        pathModelURL: "",
        modelURLArr: [
            "./assets/chapter_3/shared models/city_buildings.gltf",
            "./assets/chapter_3/shared models/city_roads.gltf",
        ],
        modelNameArr: ["BUILDINGS", "ROADS"],
        trackURL: "./assets/audio/rushhour.mp3",
        initPos: [-0.1098, 5.242271, -1.07224],
    },
    {
        sceneNumber: 10,
        nextSceneNumber: 11,
        pathColliderURL: "",
        pathModelURL: "",
        modelURLArr: [
            "./assets/chapter_3/shared models/city_buildings.gltf",
            "./assets/chapter_3/shared models/city_roads.gltf",
        ],
        modelNameArr: ["BUILDINGS", "ROADS"],
        trackURL: "./assets/audio/ktm.mp3",
        initPos: [1.0399, 1.46338, -8.9986],
    },
    {
        sceneNumber: 11,
        nextSceneNumber: 12,
        pathColliderURL: "",
        pathModelURL: "",
        modelURLArr: [
            "./assets/chapter_3/shared models/city_buildings.gltf",
            "./assets/chapter_3/shared models/city_roads.gltf",
        ],
        modelNameArr: ["BUILDINGS", "ROADS"],
        trackURL: "./assets/audio/kami.mp3",
        initPos: [0.6, 0.01, -0.1],
    },
    {
        sceneNumber: 12,
        nextSceneNumber: 9,
        pathColliderURL: "",
        pathModelURL: "",
        modelURLArr: [
            "./assets/chapter_3/shared models/city_buildings.gltf",
            "./assets/chapter_3/shared models/city_roads.gltf",
        ],
        modelNameArr: ["BUILDINGS", "ROADS"],
        trackURL: "./assets/audio/982.mp3",
        initPos: [6.8029511, 3.5857358, -4.8513],
    },
];
